version: 0.2
env:
    git-credential-helper: yes 
phases:  
  build:
    commands: | 
        git version
        aws s3 cp cfn-nested/* s3://codepipeline-artifacts-bucket1/test.txt
        aws codepipeline start-pipeline-execution --name code-pipelinepoc
        else
        echo "democid" 
        fi
