version: 0.2
env:
    git-credential-helper: yes 
phases:  
  build:
    commands: | 
        echo "CODEBUILD_RESOLVED_SOURCE_VERSION => $CODEBUILD_RESOLVED_SOURCE_VERSION"
        echo "CODEBUILD_WEBHOOK_HEAD_REF => $CODEBUILD_WEBHOOK_HEAD_REF"
        git version
        file=`git show --pretty="format:" --name-only $CODEBUILD_RESOLVED_SOURCE_VERSION`
        echo "$file"
        if [ "$file" == "IAC-stacks/nestedmain.json" ]
        then
        aws s3 cp $file s3://code-build-input-bucket1/nestedmain.json
        aws codepipeline start-pipeline-execution --name codepipeline-iac-deployment
        else
        echo "Popatt" 
        fi
