AWSTemplateFormatVersion: 2010-09-09
Parameters:
  GitRepoName:
    Type: String
    Description: "Addon name, please use no space word"
    MaxLength: '255'
    MinLength: '2'
    AllowedPattern: "^[a-zA-Z0-9-_]*$"
    Default: test
  AppName:
    Description:  (Required) Enter Application Name.
    Type: String
    AllowedPattern: "[^\\s]+"
    ConstraintDescription: "application name tag min 3 and max 50 characters"
    MinLength: 3
    MaxLength: 50
    Default: test
  UAI:
    Description:  (Required) Enter ServiceNow ID.
    Type: String
    AllowedPattern: "[^\\s]+"
    ConstraintDescription: " uai tag min 3 and max 50 characters"
    MinLength: 3
    MaxLength: 50
  DevelopmentAccount:
    Description: Development Account Number    
    Default: "040138105032"
    Type: String    
  StackName:
    Description: Name of the Stack in each AccountId
    Type: String
    Default: 'Bastion'
  AppROLE:
    Default: "test"
    Type: String

Resources:

  ResolveCICDKMSUS:
    Type: Custom::get-kms-arn
    Properties:
      ServiceToken: !Join
        - ':'
        - - 'arn:aws:lambda'
          - !Ref AWS::Region
          - !Ref AWS::AccountId
          - 'get-kms-arn'
      KeyAlias: 'alias/cicd-kmskey'
      Region: "us-east-1"

  ResolveCICDKMSEU:
    Type: Custom::get-kms-arn
    Properties:
      ServiceToken: !Join
        - ':'
        - - 'arn:aws:lambda'
          - !Ref AWS::Region
          - !Ref AWS::AccountId
          - 'get-kms-arn'
      KeyAlias: 'alias/cicd-kmskey'
      Region: "eu-west-1"


  CodeBuildCfnNag:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Sub CodeBuildCfnNag-${AppName}
      Description: Download scripts and Run CFN_NAG on templates
      ServiceRole: !Sub arn:aws:iam::${AWS::AccountId}:role/CICD-CodeBuildService-Role
      EncryptionKey: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/${ResolveCICDKMSUS.key_id}
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/ruby:2.5.3'
        EnvironmentVariables:
          -
            Name: REGION_NAME
            Value: !Ref 'AWS::Region'
          -
            Name: ACCOUNT_ID
            Value: !Ref 'AWS::AccountId'
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              commands:
                - export current=`pwd`
                - apt-get -y update
                - gem install cfn-nag
                - apt-get install -y dos2unix
            build:
              commands:
                - |
                  #!/bin/bash
                  for f in templates/*.yaml
                  do
                      if cfn_nag_scan --input-path "$f"; then
                          echo "$f PASSED"
                      else
                          echo "$f FAILED"
                          touch FAILED
                      fi
                  done

                  if [ -e FAILED ]; then
                    echo cfn-nag FAILED at least once!
                    exit 1
                  else
                    echo cfn-nag PASSED on all files!
                    exit 0
                  fi
      TimeoutInMinutes: 10

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${GitRepoName}-Pipeline
      RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/CICD-PipelineService-Role
      ArtifactStores:
        - Region: us-east-1
          ArtifactStore:
            Type: S3
            Location: !Sub cicd-pipeline-artifacts-${AWS::AccountId}-us-east-1
            EncryptionKey:
              Id: !GetAtt ResolveCICDKMSUS.key_id
              Type: KMS
        - Region: eu-west-1
          ArtifactStore:
            Type: S3
            Location: !Sub cicd-pipeline-artifacts-${AWS::AccountId}-eu-west-1
            EncryptionKey:
              Id: !GetAtt ResolveCICDKMSEU.key_id
              Type: KMS
      Stages:
        - Name: SourceStageCodeCommit
          Actions:
            - Name: TemplateSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: '1'
              Configuration:
                S3Bucket: !Sub ${AWS::AccountId}-${AWS::Region}-cicd-src
                PollForSourceChanges: True
                S3ObjectKey: !Sub ${GitRepoName}.zip
              OutputArtifacts:
                - Name: SourceArtifacts
              RunOrder: 1
        - Name: PreDeployTests
          Actions:
            - InputArtifacts:
                - Name: SourceArtifacts
              Name: DownloadScriptsAndRuncfnNag
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              OutputArtifacts:
                - Name: DownloadScripts
              Configuration:
                ProjectName: !Ref CodeBuildCfnNag
              RunOrder: 1
        - Name: DeploytoDev
          Actions:
            - Name: CreateBucketForUserData-US-EAST
              RunOrder: 1
              InputArtifacts:
                - Name: SourceArtifacts
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: '1'
                Provider: CloudFormation
              Region: us-east-1
              RoleArn: !Sub "arn:aws:iam::${DevelopmentAccount}:role/CICD-Deployment-Role"
              Configuration:
                OutputFileName: CreateBucketForUserData-DEV.json
                ActionMode: REPLACE_ON_FAILURE
                RoleArn: !Sub "arn:aws:iam::${DevelopmentAccount}:role/CICD-Cloudformation-Role"
                Capabilities: CAPABILITY_NAMED_IAM
                StackName: !Sub CreateBucketForUserData-${AppName}
                TemplatePath: SourceArtifacts::templates/create-bucket-for-bastion.yaml
                ParameterOverrides: !Sub |
                  {
                    "AppName": "${AppName}",
                    "UAI": "${UAI}",
                    "ENV": "dev"                    
                  }

Outputs:
  PipelineUrl:
    Value: !Sub https://console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/${Pipeline}
